name: Daily Commit Bot
on:
  schedule:
    # Runs every 2 minutes
    - cron: '*/2 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Update timestamp (24f1000322@ds.study.iitm.ac.in)
        run: |
          echo "Last run: $(date -u)" > last_run.txt
          
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "24f1000322@ds.study.iitm.ac.in"
          git add last_run.txt
          git commit -m "Automated commit: $(date -u)" || echo "No changes to commit"
          git push
